router bgp 65000
 bgp router-id 192.168.102.1
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor HOMELAB peer-group
 neighbor HOMELAB remote-as 65001
 neighbor 192.168.102.31 peer-group HOMELAB
 neighbor 192.168.102.32 peer-group HOMELAB
 address-family ipv4 unicast
  neighbor HOMELAB activate
  maximum-paths 1
 exit-address-family
