creation_rules:
  - path_regex: talos/secrets\.sops\.yaml$
    key_groups:
      - age:
          - age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
  - path_regex: argocd/secrets/.*\.sops\.yaml$
    key_groups:
      - age:
          - age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
  - path_regex: docker-compose/.*\.sops\.(yaml|json|env)$
    key_groups:
      - age:
          - age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
  - path_regex: scripts/secrets/.*\.sops\.(yaml|json|env)$
    key_groups:
      - age:
          - age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
  - path_regex: terraform/.*/secrets/.*\.sops\.(yaml|json|env)$
    key_groups:
      - age:
          - age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
