configs:
    secret:
        extra:
            oidc.authelia.clientSecret: ENC[AES256_GCM,data:l79BbDMjWtp9L0qujvsKZVQUBfqE3TTs/Mq5D1tZiuwEk18m0Sv2HA==,iv:CmmQ/nQYsNzwSsOKblRafWO1p43g8Ba6AA4qaDmLPSI=,tag:nHLa8KXwhPKSrfhjgr0huw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aGpkQTNDYkRKazQ5N3Mr
            MXJJdzRUTC91bC9RRm9udE0wbDdoQjk4b0E4CmlhanN2SDNDWDUzVUVrcytHMzY1
            YzRoUmJzYlVta044YUg1bTRQRXY3QXMKLS0tIFNRV3dTSzltNXoyWGhKS0VsQll1
            UHN2U2p5VExKUjV1KzFDNU8vUFpYeTQK2toPvj2G16e67PtLM7yIn3WZRBtjxNeJ
            R3FxtsqnAwLDowUD8UsaM6mh4lodlLIhsPbCLm2OHAXBc6a4qVnHQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-13T17:41:24Z"
    mac: ENC[AES256_GCM,data:UuHX35UaJe8KYTbz5duEN0j/U/UeDzJy4hM3aZjuxQIAr1USULyzcdFoeIwrZXyxCIRXJ+lrZKPH2ThAMAakn15c6EMmayasSnPX96dtohCk3KFlEO+9oGf9bGXnsSnZQ3UFOT5Uq9K/8ObZ0VScHZQicuMsbZNb07EaWqjTp+Q=,iv:aDlf62vs5XAmsrCWzOeXxbah4gLtYWBnE8+kYHbZarw=,tag:eeA1AauGt9z4OYHvbDu1hw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
