apiVersion: ENC[AES256_GCM,data:KgQ=,iv:WTY3/RrvoUi+tFzy+Dsk40tdm0FqNaL3tEGjMzmCzH8=,tag:ZNF7VnMzowkieb/OhdvLkg==,type:str]
kind: ENC[AES256_GCM,data:a/Ft5RVH,iv:IF02F16QdAiAYz/HMWrLH06UUysaQsWp9WNrePHtWg0=,tag:cUdtpzDt/NiowS89/4W0YA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TRFXcFeXZs/at4G4whlzGQ==,iv:+PiiJNyTWeh2Agrbo3+k775+OfvdVA92gS2I1M/MEhQ=,tag:Q+mNzQKK8pNXr3HqKgjX0Q==,type:str]
    namespace: ENC[AES256_GCM,data:+SyuAX9o8tk=,iv:ZOSeWM98ZVPyVmamWuo8MsQ0DR4s6cJBibs+Br0+Mzg=,tag:xT2Q+hmud7Hd7woTVt/WBg==,type:str]
stringData:
    session.encryption.key: ENC[AES256_GCM,data:tBQxddrxtAXTGL3B+l5DT8oHUWSfa8J/VDdME/A6CqTFUVXQic1KqlZTxGL3tNrui9olW01KQ4LWLxhWDx5S5g==,iv:RJ7zq8mfe3WN/ZINQ5lnCSiXyRuY4J9Vt4zEL620spE=,tag:d4brci2GRb1qNUi5/ahrIw==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:1AocEJrJKK1dBYsEiCHZbh49AXtTnNYj/2iTCcy2tr0rhcEXDa2AaEDsREAPZ1xuhgw+X3ytNGgeu74l9OkEuw==,iv:qFOI6ZWWSGSOR47UNWRFKM5Gdom/NZkbHt/U8UjMi+I=,tag:c4xHM+ELVOx0jMSEZvqI2A==,type:str]
    identity_providers.oidc.hmac.key: ENC[AES256_GCM,data:N/QabTWNzG4gIRXQ6boH5R3Jj1AOqeBlUyEciwJTpveNQ3eC2CQ3EIf1fqXRdEyiRZLbME/64BPu17EZyNZxiQ==,iv:l52LkLKe6ngZw4yzKiKFTOrVcvgvk1pnFn7pdNBAmmw=,tag:bhW1uqkmOzGhQpqFS/OS9Q==,type:str]
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:IZ4IkmIIODikbYRZ61qEcoPYL3PJbAeW+E3kHBpUUM2NFio7dCOCxzTLFlfDaUQImlP7S6wwjFJnzKdx6oTLxg==,iv:MMTbCthIS9p6sFNHtSav/79FgSgW7iw/oWzF1Rn7yPc=,tag:f6SkXpky5srntdeNqFNthQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4djVSREh2c3lvVkFxaEJY
            eWU2dDBZd3VlbjNSa0pzc1MxRnZyWDFmWERZCldTcE9XWmFsQlJEU0hyZVZPOGVx
            cEN4Y2lKdUkwcWxtVm1nRVBxb0huTFEKLS0tIEZDMUJ6YTA0WUkrVFdwUlNlVEtz
            UWtTOUJiaDhVM3RHMVNSZm4vOUMzVVUKa4nJuSXje2Dulxwst7fJW/lUC/9JnMpT
            QpkSKeD+uoxOQ4aDq4sEwKFXGCKdQK55PiQjPSJ1OCJxVvI77SI28g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-13T17:41:24Z"
    mac: ENC[AES256_GCM,data:Q8X0u3vxXTGCLoSMzDuFQ2cD3lKtaEa1kz4QTdYwtKNAVxf1YXMXIk0jb0GF/kTSDn2vSx8SjIQ4+/Dpfyl4JgkZYdgYp2ran3+WTENypmJPbLR/0PT4oiZkY7GQIDTH2eqhxYeyEmX0qm3ml35rckjBNRo1A0tQTcPsryehPWg=,iv:OBIC65m6UKVUxwtxT9dzPzUfn8qrUhRteK05Bu0vIYg=,tag:9SlItk6Pt/H+dXrDBSI4KQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
