apiVersion: ENC[AES256_GCM,data:Aag=,iv:/UmMBSTM9uB7CNrUOHWdN69voFLZL5GwfjDs/XdGdZE=,tag:FuwiMo7yA4Yu6eECzEVljA==,type:str]
kind: ENC[AES256_GCM,data:3tHlAUhY,iv:2YFQzfz6RwWkZjnst+q9bERUAmZIu7fbclCKTKGXzTM=,tag:UclnCCa6hpH92ssY8xILJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DWS3a+jCl6XiovuvlWw=,iv:gyMo0kGKTdkfzpzMUDbbS/jtaDyUuovC1T2Ch3JuAQ0=,tag:imk9oNNh+fGmayVOSbjNZA==,type:str]
    namespace: ENC[AES256_GCM,data:NoQBc6oFMrM=,iv:21CWT3hNebHsUtdZXZ/bzi+z/v2UTYvF7ewDQUtID0Q=,tag:Iwvh6AxQDlBixVr439957w==,type:str]
stringData:
    users_database.yml: ENC[AES256_GCM,data:S8QEvX/+Zn5U0BAF/X2VFfLdFd+veMITfFWHNjCgC1FQl3gHM67ufopzMNGih4lqXbnaosESeUGovMKey1E6rBHSjmEpU1w0JKdzUOA22lyHeQgyphbfPXhwp78viFzfHAxUgu1xWgOztszuF9CFa3NQJcaNvMD0iWEEeXNklaNpcBVYJfPNd0oZyvcQ+jVaaBYhQP0v2MiDL9OegWhySxQkAPt0vZ6AVQJtz1v5g0qly8n0WOyH5peimB1gee/xMsDB+VIMArw7fmUx+fkAXhYKrb132Lng9zQ7OG+xhULZYOUiyr/mV65JIjijveE=,iv:LDtXVauYLxmj6ZQBlPjdIVOD5wcmI03fWqw8KzmceyM=,tag:zN6acH5UOb9/BCdG4dukwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUnhlZFBiOHQxbndVZ0tQ
            QmthWEhITUlaT24zb0FiNzZoZmFvMUdSbmdjCmYwODhpU1gvT1N3QVJJTlgwY0Nn
            ajJIVjZyYkk4d01DNFJOT2g0Q0NsNjQKLS0tIFRpbWJaeHp2c0ZhMExtWkNYcmJv
            RXM1YWxVSjA4U1R5ajdaMHE5MmNvclUKjZn8enBY8Kr+BorQNhL2S9V5pP0P11B9
            uMfu9QmZ7r0TVMUzf7nlrf9Z1wlYmuAkBo027upBNHV8Q7MprI0paw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-13T17:41:24Z"
    mac: ENC[AES256_GCM,data:rBG/oeNdQEmmBi3fDOdAFRsepTlNn3uVAkCL2fl5x08VQWJkAYLZiawby3l+j0IC785FBELwXt/MaKq2PQ7l1UfiugbM7gi+DQAISf68FCMdJnSJzVnQofRTKqGPL88lkJIoUFy15zKZY9eUygvtxUMcRQl/lCAupyHnf5XZP1U=,iv:RRqMsvkr13tcUWLJVbWE6XfF4ccft8QJVDEmiMpD+xU=,tag:7pJGD9y1GV+cMCRPgCD6+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
