apiVersion: ENC[AES256_GCM,data:g2o=,iv:MyU/Ao5vQhRcqG16ozJeIAoipkscz0qfTaDJwAE7N8g=,tag:3A7MycKVYJqL2//5oB7Wsg==,type:str]
kind: ENC[AES256_GCM,data:+c4z9l6H,iv:Y2JrY+ejNdlQF973+K0DKpDrGcj5uc/CeFbcCHFgzAA=,tag:QDEuOw2/kANA2O6fgTfc8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MCecoQCPHqH63ZvdDYVo6hPYgZA=,iv:JlC7N5lBbjw0vkMRS7ZtZETbA/O0SYLVBDw6AGzX2o4=,tag:i86ZIfYHyALHkG65ftAIYA==,type:str]
    namespace: ENC[AES256_GCM,data:3345CVHZTNbuOrf3,iv:d6KZhvsB+LTgf1g2qnsxCCzaN/hpZpFBFjUAEtj13cQ=,tag:yXhVTJXgpZvn47GLrvY4QA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:8VBQfLxnXb++zd/U1HwIEidOlNYy9d7q5a4zODtGmpJNdogki8tEzw==,iv:SoSzeO70c8qLwa2ZYh5QXi1Nswc+C8PRRb04hBLevLA=,tag:BbURg8NeoAjHXIqK+jrNnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UWE2Y0I3cGpEWGprd2Rv
            RFlaZjFEWVNtNUczWlFlN1ZPbFFLUzRmeHhFCmNTQ2E0M3NIQ2dLZDNPaFZINlNl
            eHd0K3M3YUlYTUdYNHYzVDE3dE9ZUjQKLS0tIDVzaUM5YXFtUEJSWVJlUS90eUtR
            VUdGcUJza1JaOVdhNyszSEU1WVl4Vk0K5JUO7/BVqHtdOBgk1H6r85cPDWaI8t1w
            8FKcv5uBQe9LhTvB3zcoFsgie0vnSq9RqDywreHWJFXx7oQbplhbTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-13T16:28:52Z"
    mac: ENC[AES256_GCM,data:NbZEVooQDkF7XKgczkjSJIPRwOZ0J14IBnQTmAMEG5RaCKFGpiprlZ5gSqZtmK4KVGEzOa9VwRptTwTic2ngTDcbRjOgJrmg2ffyf9BNQvdewZO9ucKp+yAhXTO2Sb8phxpYDvqMkKF0df1HqXRsh7OPLZbZSzNHq/BLI1KhgNY=,iv:YoBuNmsrRdk4Qz93ZTYT0VTpZ7+b2Zz5JWoBwdvFXQQ=,tag:dYPeAb8Rmt+QZo+NU80X6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
