apiVersion: ENC[AES256_GCM,data:8M0=,iv:l8qFNc+OdJMTcEtS478NBlYVJBdQeQ9VEPpS0MHU7d0=,tag:fhh81h6maMqZryb69mySnQ==,type:str]
kind: ENC[AES256_GCM,data:F+QfMEuV,iv:buO+V+asEe7zSJK8CcwR1zPTTRj1MPd2tnr+BMWbwiE=,tag:KukQUkcbMAUrbUtZe53SRQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UVriTosW0yfo17sCkVS+B2g/GNk=,iv:Ljsidqv2hi8cZW3KTUEr/L9xXNygHcNKcVGhces0vAo=,tag:fHPu1pyD+PqUv7TyFFcF2Q==,type:str]
    namespace: ENC[AES256_GCM,data:jn3HNN8mvIFQl7iQ,iv:1hnYQgCJ9APpiiw0u9v3ZQyeMiePvPgiFptzQTxp2Kc=,tag:6054WijJMmITUUYDNe9RIA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:Fd98pv8BlTztBufN4C/JtN6nLDGhtzY6/hMMeGD2cWALBeu3NxvfPg==,iv:Dd21xZT7+7nmmmZYYkL9f1FRMdTOUpWt1hT0yrXbaGA=,tag:87Q0HCwzejU4qgHZV7up8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y0drQitnQ1pUa2Z0Tm9m
            cnl6a1RaZlhzVnpoZWsxcUM5ZkE1ajFIS2prCmxXK3lDaE1WWGxrVzdmaUhWVytH
            S1Bod01MeVpxUUdLbmJIZmpPQmZuSHcKLS0tIEk3MFphdnhCNjYxTXZsWkhOZThU
            SUJpclN2Q240dmQ2b0JINHNUZlBzbmcKJiD/STKcWOdQrKwgThxAYX2SDLx+fLV6
            4wyB4IEGvScmwfoNFwWHzrOVkgGHKaBK5OphRr33bsakI0NkOgggAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-13T16:28:52Z"
    mac: ENC[AES256_GCM,data:9Enjoy4uNACz3kS3q7aBn2yKlKZUimjuQWQASTEWkwtTxSAB1c6Lr1r2a3FC413QnpVIGUeWfRqbPHPQdAZ+4p4byVTi8cLwcnTfSs2QN8bIkj/smr8kSGkEFXPOQ22Q2kx8qAKaYsE1/9ZNDuYfxrRhmdB06heNlzu/WOa1nas=,iv:8vCbPVcAPu2Znphwgts/j5lPA6Yi6LFQa5gH/hNtYU8=,tag:uWPQ7/Z8hQKdVjLusey9dg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
