apiVersion: ENC[AES256_GCM,data:wb4=,iv:XjgdNQiSVsSdhJlgFsx8jXiyJBHazqBBLMxMoFcJohM=,tag:1/SJoHgJ741zCcj9GUbiDg==,type:str]
kind: ENC[AES256_GCM,data:JsdAa0PM,iv:mdqGyMiDA8pyHjZalAzQ9iVcKDmnWcjZ8vXs1ZRnZNU=,tag:iYKuZfRR86TvZDhfwU96yw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UwQqSpA0DTieqHmM+J2vvcJzBi0Qde9asDq+,iv:ef8SG0IQeDeTu+skXI+dIJZsEWcyffUnrQ1tvkjk1NI=,tag:o/xG2bzeRE5anefQcbbMtw==,type:str]
    namespace: ENC[AES256_GCM,data:cHkZKwLnrIA=,iv:vYWVnpbg/EKWGB4Nha9Svby5xcL5M0sp2BpLIHN+eNs=,tag:wQU1lc6IUP2A9Uu5f5Z9tg==,type:str]
stringData:
    client-secret: ENC[AES256_GCM,data:o7xyAwdVmX5tWenPVyby41o0lr+0/Vm6xP3XZ+w6OCUlDdnrnxoxQkyT2XBATg1S2Kptje7jRvS1NRk+vER2jqDFckP4TPrq,iv:foATfo4a/aBsk62HJfbrZ5rZwryBjBxZuveEEkbu5do=,tag:3CSsW1oBn7ZjNqMoCuSD9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZDZyU3dMZzRTcW5XZTY5
            NUlBcEVnaC9pRk5xMFQ0cVZIazkwT3IvbVZnCmVXVlhOa1kwb1lpTFRsRjBCeUky
            Rmh3MTh4UXFMN0UwVTRXUEQwSlUwYzQKLS0tIENNdkl0OVJmbE1uKzRGazZrUWpm
            RVV2bFVWSG1uMUdPV0IzeEtNRkNoYm8KXu6qVJ0pJkSJorRSrEOeCUzgaLNX4jmW
            +HP8apK0EP5DuX66OwlEdAFD1pMXlrl3xEQXJ6Gqz18PFiSx6WT2Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-22T02:08:58Z"
    mac: ENC[AES256_GCM,data:9KML8s4dmJ+mM2NYx8ESmEiyVE8dDas3KmCwle4BPK+40yLGUHfT4uRCFyPYqWyLGUA+VjeUJjIPHwwt0HQb15DzCyQ/4KOJh8MG/uW9V/OojvSPCXC+eMiHv5lEzXjT0O2FbOUvxilVjiUWRifnPn0B94F/78CA09hBfGweI1g=,iv:MsMKbrDjry1fqAndolbLrz5DVSkNgrHH0/owYCaqeok=,tag:+uCyt5fnbuDlcETvkV+5VQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
