apiVersion: ENC[AES256_GCM,data:Ays=,iv:/RFp1Nu0eucaJL45NBd3CLW5osbAkwLn70nwGPW7OfM=,tag:yVMFgteE5nvf2iHS43nCMg==,type:str]
kind: ENC[AES256_GCM,data:OXtnT5mc,iv:LEQuUyt9/Z2l+GridGvXNOVANCvvgdYFmuaPd3OXcys=,tag:6AAo0BaMH37DEI4FhcQaDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NtVg0+/FN2MjINgvawVFoTxg8Sd/i2Jkht9p,iv:MaWcA+n72Ube64k7LMgDOq4+fZDNxPlOWwu9Ng3jzSI=,tag:ydk1puvF76ZpkdTGvAeMSQ==,type:str]
    namespace: ENC[AES256_GCM,data:kvGgGp7qvwKvk91DljtRCA==,iv:mVhkBbV0un58Ljqaqc5u1qPg6tvOYqlSQJ2QoY2movM=,tag:Kivpqc9Ah2AdDlgU0NwB6w==,type:str]
stringData:
    token: ENC[AES256_GCM,data:MbQNZrBiJwuomkBktszcIDvwjC9zxPZ4u06yw6NEb285YCnCJsqbSJ8qbOoGcaSyGC6NIN8QpT1Vq9JMp8rEnZaKIzUCxX0FNeJIkto4lDNs7fjwODNg8ipVP5qsv8Uf76wz2+5ss+Y/YS0cLIEueGItVscN6RYbqi1MSRjOq1g536y/eWhJP2yB/NcI/MGVLKkZNkUOxk32+mGKgPyZuDOSp+7B/qgoUUHwaQGTTdy30yh65TfWr/QSGrm3Lu7rdE/JDlyuvPqrDmFPN9HKwzkaTYJhkK2B9vRBo7LpZq3M2So7g+clTWFhkcUSzqxfL2scXfFFuHz/XlbkxW3o6TjLpxVo3rRhkvskny7dzmHDyaLq2b6XmUg5rWWIy5pnPg8hv4AimxrxbtRmRLpL1xAmpE3m0BNa6g7Lh6ub6vAgQLGp7OeGHCoQgScyQ0eQGLoYpD1u98ANmwLHI+AKLY9Cnqgyw+fujQ2t4HbUEecyQPFMou42PI6RF+8ZP6jWqTCaGDqh0IxAq+LXCeMdW5QDigLTx1HFSOLSS/qcs8ab+BXjFhri9ZVwFgGdZ+gC6VJi3gUjHbzgGGwAupQqAmCTmSUgll77s/OwLE0iYMLOXS2nadRpD2PK5pMJOKoHLcK23m7XCzFPI1iLQtQ+EwPiuJku0hPUT+r2Sa6oQINijvQ3MM4s8UGWZOC3uUx9zGQF+/fIVCFmlBNc7ikRJYEcIAqUFRHfVbTHw0EG0HUuLzIlJZtwXfzci/YcZ5ENR7075yGP1gHc82QgKwbqAu6SUEXlC0EtWy3gUS48RlQ+oFX9xzP2lNOzLO7ti7hoVRuJ29FoeKW30o9zs6HEhYIpb56WV9Z7zcCSP+V625aK5HuJ9ZEYYvMvp9HO/4NTaH8/b5TpWA+diFLB11I39X9thvkL6AJoG4JX8LbMnqjg/5xuy3sleMXQecnaJb9DLesFXGkEElKN2F1uXBGbYJYknWB1jJmjiMLQ+NbznrAtaLlShC7/tp0VTh4SEn3YQo20ETEhHSiAJl/DmcoyHD2SQ9a6jdkFaFJIjRcU+EteJyCkyEw0F9fk6FjGB6uW6vDK,iv:qiuo/wddnGjJGv+t+E0ICUg/K96JAkNnytXB1CAEeVQ=,tag:sqgeuv4kYaM9J27mVaLzvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMXA2TG5iZlFwc0I5YXFq
            MUI0MDArZzdkWlhQNFQ5cTNxdUtEdDVHT1hzCnlUR3NVQ0RSOGllWFA1TkU2Rzgv
            S3dRRUhBT2VOREN1QlJZWkhBQ2J3OGsKLS0tIHNKcFVEc3huLzRlRkpDS2xWVUM0
            RkxuZFlEVitEa0k1YUpPa1hOKzhud28KcqBqz3s6kbAgBOFGp/sASZwV9NoWzuHz
            B9XFTnbPocU4t0c1zCfPubP82QjMxDUtFTJBu040IL/frUsReygoCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-25T12:54:28Z"
    mac: ENC[AES256_GCM,data:Biy4ZZ4kcnMugJSAQXmzkKvtEy3j8r22ngC0KAVKtW7Om0+22BcKtAtZ7PyEt/JDNH18E7ttJzSd1hdbDqNP4yVDQ/ftD+p6pMei1ZzWuGoBeEj7r038sXDVYr8roJ70lBjyaAxNdZ4zULdgbXmrePGR/IfsUo0ZFWPedeABSdE=,iv:vIKMAA+C46h2IDLwmGSmR6Yia2GACVBubbn2Cvy8ZcI=,tag:tz6RxpWSw5QTS5Db22IjdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
