apiVersion: ENC[AES256_GCM,data:rPk=,iv:RpTtUyIvzcOFjFKBx/4kRd+gmmVr5SmqPEBvMcaB1LA=,tag:OO+k6IWgsN9RxWKbhOsJfQ==,type:str]
kind: ENC[AES256_GCM,data:YiBOhANQ,iv:m/Z8jkIwE5xcvAm6VjHL/Zv3j052Jju09e1o53N5vGM=,tag:oZ5DWzvO1PK5VFlD/UmMqA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CeFGKKulGop5FK9Y/NmFuuXfxLMW,iv:qXphmVqKOHDZslz3qLrwGGKtzGSIIJXrBuGHEVI3O+Q=,tag:3NLHSGk8S9QQ7rHuoOBvZw==,type:str]
    namespace: ENC[AES256_GCM,data:Z/e0lTBaKEM=,iv:gqiDl6KCEYLK244gzqgYKglEjc9R9CXXbamPLGmO2rc=,tag:a+bke9XcKVpJJBHtQBcBZQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:5Ft5zHJT0og/DCuUAYkrcsCql0PcuOYb76jcFaairnBotOB/0Fi7l3LcjTmYCLXO3tmx2ppvm6igMQTmLO3+yDWeavgR6gwMhkbxMmIjC7pHvIlc/rVCD4Dc+8d7,iv:gn0OSVnpBDPiOghkiUXxpa24E7T5HL2BbXDEe7Pqj5Y=,tag:UC5Dnb82Q7muSmjwtRO5Yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZDJLUkE0ZmZNaWtBZ1NR
            RGdDMkFteW5hOHlGU2pmRFUwWEgzSjlQZldjCnYwNTVab0EyeUNNQ3R5eW9vUEZp
            NkkwUllXZFVMc2JobkUwS3J2WGU0QlUKLS0tIHZWSzlEanY0TTJGN0w5c3BlMGQw
            d1BjVTRiZXJob0hJdk44SVFGeHcrZDQKGQvz/146YWqAXucbAyf8TjzzJXxmERRD
            TA1NObGF7kSlYTBYnEeIpAVemNDj7zL91XCCXc3KuT1gQ3vaDPlhqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-16T18:34:13Z"
    mac: ENC[AES256_GCM,data:cahhNJKIZpfxJHmlBB13+gtz5n31tZ4vWy7DVSoofxNRVNPOv3ZpaVnhKCUwAb3AnwkQH4P6gcAs2TI+YRm22laczdHQDmeD9yrCe7TJEuMaa0XiOB6scJAQonfhwSYxI8V3mVvBxEJ7pwzX+s1EsyHhWYdD+Xu5d+puAc7seRg=,iv:aqu3bRG5ILXTG3QYj6KcvrfBof17ubxVeBqXgFdETv8=,tag:zsXSiUoKUUk45lqbknhECQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
