#ENC[AES256_GCM,data:VMEUScwaOYYUVBKcWPfgIN8DY1i9LS0h2nx/QSJY3HCbvXNbEHh+bIbjYWDEpnwasvhoAFf7xlCHAGktGl91pVY/yb+XZH1ivQ==,iv:OamiBFkejFIhFGZf1upXI6kUEwvTF3YEjYVAt/dt1Ko=,tag:n5wG/Mf5NOfEwPaGjwa23g==,type:comment]
#ENC[AES256_GCM,data:IL+rIdVZ7+CanPP71Hbtd5WWirpJuMhN1/QTPDCavwU+DKs2OTnmLKgyYPlQ90F+Jq7hp1leKFz+1S6XKVPOz3gweb6lZXtr7A==,iv:rI5qHR3PJlCb4hDt7qOiOWEPI0lL3hJ6hFV3SicG5zs=,tag:jgSofLAo+K+vCWf5HvTMTQ==,type:comment]
#ENC[AES256_GCM,data:z8H+NlfiBFhD0eKAd1H+vJVoohqNRZCJ/cV2N0dnPy0K2ZK0AZJQ3i4djwSpbZN3D5yriSFtXZ2lPsw3jR3hseGlC5ku9J2EYj8=,iv:xKJngJHA01ondCJEodoQYxp7DbpOdiRzf7g6NOQGxK0=,tag:zKQfVxgn7R5auR5Ocgp6qQ==,type:comment]
#ENC[AES256_GCM,data:YZlDhee0SrX/A7ozob7pPWU9czNtQfa6/zXmk55G78oqTfRxvsz/D0rFA58Q1mtnv4S52xZZDGxPGyMuyOYguIV1Vw5A/6BzJg==,iv:J3QL4grZ75dqJSS7WrGDMm8OKLy0+EvwrxeO3bvqPcY=,tag:j/qrlISWmOOdHDEOPKvO8Q==,type:comment]
#ENC[AES256_GCM,data:7kyaJfTDoDOUxd1sKmd5WcRlVKerAveDgsma1NzwM/LcZsNsrBtC6VU5H9bnctyOM81WIdjGWtuxkCNtQPULIgEuGHinGcVMOw==,iv:hCI5KSPWfvu5cqeAbDxo1Q1iglinJQpwlxL22kV8uMg=,tag:zmnYv4Rgdk7fwp8amyK6gw==,type:comment]
#ENC[AES256_GCM,data:w24bY4eQ+PUpS0oO104RIjuutcI/8kspW4VafHPpA9sb0voIXgxMtCcDDG0tfK19GHRi9zlwn7B/,iv:uExmXgN/uE3eGvIeUYKyFY8fVQ7aIRrxb+VDqecAsSg=,tag:5Awgi7+xvGyaqna8dQ8BSg==,type:comment]
#
#ENC[AES256_GCM,data:Ln5xf39v9LtI3U0EnYXdtn/f2yRuCk+2ax/p9l+XUaS+8pJUMvZbdct1uHZ/kCoJZ9RYcgqW2hF6Y47oy7h6no9L01/xmOQ3YGg17w==,iv:cJ59FJa3n6wDzrEI4r/mfukPOKJiG7yoa3RVfhEUxJI=,tag:EF5ac30eTCAIum/x7Lixpg==,type:comment]
#ENC[AES256_GCM,data:t2k0uOr8T4ClgqUVEb5/XCUHBROBQJRm3eUFImJB7pAH3ensqS+rkcPrRdbffdgnlidvHqmz6A9dPi+xmSrVrkXEMKHlPngn,iv:nYFVdujCSFQAOJ0FAX1ZUYP0HZOjCz5bANIqkrN2c0s=,tag:zm9lhMbKDJ949IkyUgZsoQ==,type:comment]
#ENC[AES256_GCM,data:jlL+kAjsvUEVAeyK0lYYFEJOdjGI7XJIioH4ApABYkKUHBlKPG2C66zFNtKNJlPQJ/43anKF0b1EtROs5wJYMB4iRa72S4sK2JPKP10=,iv:LCp1obz9a6eQoJxOS4bKoFW/c7/DT0T5Q0coRXPN4OI=,tag:zkIDE0N8Ncovwj4npSgyAQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:hxs=,iv:uLftTiw+DP9FXeHST++qZ5hFDIRZVdNVg3SC5NHcMxE=,tag:CbFF532fuMhQsdG+9HCxkg==,type:str]
kind: ENC[AES256_GCM,data:EMvJwYq5,iv:pd6u1m8sR9wn6FvHucBrMcrWLzmHqOLDOIVbFnNdzks=,tag:n+nsv5B2p74WWN1vFZTAkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PrU+rjCSfAYaxil+jX827N5X,iv:LCc7rrOD6V1JrJlI3pCYPOQYch0JVRn/8UYseSVby88=,tag:IOIeczP+kRTdaPU5dVZi7g==,type:str]
    namespace: ENC[AES256_GCM,data:8z8uM6EIYQ==,iv:CxYelTXfz/OUQX6pj6HP/u3T9wcKSwUeHM7GAjY32Ug=,tag:+tjQBBvKdJB+iXpA3H9ZaA==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:nEwCWg9EKai43iZG9G5Qhp3hysrzXHuK3gJfTEi7Hh8dXMP39wKmKA==,iv:qoOG0ncxo78t7H+qCEuY6deJY3iBnVSGRSscMZF9FKY=,tag:PsRxehHn55/qga1iKszzYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYWhLbHVUbFFWVFZpU1lR
            VmpoNzY3UjhkbTZMOXBWUUhwNXEwd05lK3o4CmJUU1RCbklBa1pSWHFMdDI0MFpV
            YjBsUkJpVXNCUWtieFFWWFQ3QTVmQmsKLS0tIDRVaitCRWFFaGFaTkpYWS9EUzE5
            WnBNekRSOGhvVVpmeURKaVVVdFBiNG8KfxmmXMTE9t4K6TlkT+KF26vsTfzaBEoq
            LMlsCU/0P8GZOEaljhLHCGunr28OG1EFSumqH0GymuiYho4REYDd3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-18T18:33:18Z"
    mac: ENC[AES256_GCM,data:Lgsm5diGSSXznPrTds2+bnsqBrqaXlrwMbeMXzovyfxUW9TIRqGsgq8HIuw99TFIW5bLFIWmFwbXQRqV06dXnCvD8uzLODvNzZ6L6okyaj32M6hPr7J+PFJ+TGIs5QQvuZmJ0meG4jBVQvDP/3Adw7mO5DuDQbes0FkxPzfPqGQ=,iv:I6LwXu2R0dn4faz/UZJwfL5BJBONFEQpGc83kjZb1pE=,tag:LiLWIVcCPnJ8qdW4ZXmIjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
