#ENC[AES256_GCM,data:Gg8C3guPVIvnAEQ1htW7t6sg/SZmSVg1hxUjBITStQurYTIaZAv1J1/WbvNdzX31ZZWJPAhqh6xHEcpBzIJDzDO9XGGiGaI=,iv:kygEdI4PVa89ciG3zmy5BkFdR5NsVK2dXm8SSCY1uI8=,tag:tGE0t3IxhGvY9xx4rPWrwg==,type:comment]
#ENC[AES256_GCM,data:PQbQTJctyAaFRAJ5F2GEhHd9gWatDoQF7kNj5IBd+0Vp++E0Bn9KLCqsoM77WW8uDH2c1B04EZX+A4z6LJ/AnZP64QAywUyV5TI+,iv:DqnPQURtuw5sLAADE+2o2adi2pzBj9qlP/gKYSzG8eA=,tag:kHCh95P9t6xg5KpSYo0inA==,type:comment]
#ENC[AES256_GCM,data:Idv3GdlrdcqjU+N0OghD5E3OjaGApEnUxoFTZ2ifPYZTxhLAcx0fAaOatBAADskZ2KwiinaQd93j1eMPmPeVjxmyH1pgN4vWbA==,iv:x1XrUlIDfFHyjDOnw5qgKXJ0454jDlGRtyk+bPLA+e8=,tag:DCrGu0BQV9c0iKXIhUmoTA==,type:comment]
#ENC[AES256_GCM,data:d1UFPEgFdAWmcCFCjTgvM1uAkDOocL8WONjnJtLmLq2hNGX1V4Ijo/783ma95XKW4E/mjthHrQz+wEAWdpVb8nBeYyyS,iv:tJuRSV2kHfUWokqhIV2ogCHmAEaX7KKFFieEhCn/dcs=,tag:rssHXdDVAQWlR816ytNwsQ==,type:comment]
email: ENC[AES256_GCM,data:KrqqFXvr0+Fu4fqIweVBv3H9,iv:LErOxB8Mkr2tLLeRQZm1F0aZ/Igojm3/eXy42j5V46E=,tag:+FXoU7cI/uKZNPnWy5BD4g==,type:str]
password: ENC[AES256_GCM,data:mC4A9GYtQ3ekL5qQgFe4mqkBpxivuWVLfiXvCmE1+iI=,iv:9tiEsC5BG6Y9dkwyu+8QxGMdz02/l6Uo3sFp/OI+ii8=,tag:gVPMfAPKlFAkyI0uBqZ84A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SzBHV0lkc2JHSTBIaFVt
            Zy80dCttbERWQ3E2VkdKcHRUSndpUEFMUGgwCnprdFJZb1JldUZwOU9SSUhmdUgv
            ZSs2UlMxVjJqSlhLTzlKZUdCQWxwWVEKLS0tIHpUTnNJU0kyS1RScUxzQW1TbEg2
            QnVyTkwzZGs4ZEJ2byt2TURrdUpkazgKY1zFC8aIV0H5aVw2wKDfMZGzDPqs1QjB
            4jtPeMR0K8/fKVa0D1NRx/h2TFThblrkYdMiqcgEG2jyzhjYcsHiew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-22T17:40:21Z"
    mac: ENC[AES256_GCM,data:QCOoOCu/V8y84bn8cC3p9mOP7JftbmQ6MC7C2sy4Uy0VrA8X5Qlw3g7WrcTO0NpiuQZDPXXseOBZ2hKDNd1OLZQpvquT6BKfkR3undDYHw+vFjCQeryo6jPJoOtNWhqvUas1MZjCxnOyQrrCkx2r8i80dxWG8qpuyY6tqj0xMuk=,iv:x/ZiNAqQ1RXB7PSAVyloN5BgqxbveGXDlmNKLPatdhw=,tag:QLKwKvOrja5PhpFyAIbirw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
