apiVersion: ENC[AES256_GCM,data:y7Q=,iv:BaOkfiw2A2LGTWEAzCnTaBJGOibg1qHhD9xQYDeMEIM=,tag:kQIsf10OyQIKisln20v3Cg==,type:str]
kind: ENC[AES256_GCM,data:8jO9tJZL,iv:RAonssI9xCgdXE+EgN+lnprU/GpN+fhedpu14fDOa0E=,tag:GZuzN8GtvNoypZcoW2sMaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:m9IrEv92/gRhZXhCsF+PYCXndhQ1I1bJ,iv:2ZaoEP3yWGkEhn4IYXYzQMclOIoRuuLFPwYnmmEuJKY=,tag:gntE+jNbbitiqfIsv/Rsgw==,type:str]
    namespace: ENC[AES256_GCM,data:qVN0ie4w5qZmpuWPTqmklg==,iv:2IdVKvSsavnbs6iBULIjEKZ+0mbKPQuhYrjLJDO1hBA=,tag:vEtNlNaUuOTbgYfrCzxZKA==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:mYSFVsOPMgkcHWk3jeMjfbeJYU7NMC7lR+KNlbPK8IUf52oXAGIF2hdC/2Hw7L/Ycsn72Y1iFcQCyhXCm4H9fn32,iv:tLi4FkAM6eV+96Prsss9PzjL3EJzfZWin5Hr5dd1ITc=,tag:5OgATNxnjIw2f5UoteQ5aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRlZLejZNdnBIaVUvbWR3
            K20yTTVwV2Q5ZlZEOWRBb21YNWxPd3BPcG1VCjIrdEI2bnJpUitsLytrNjhMNDhR
            MjZzZmV5RnMvamUyWGxWZ0NCam1qMlEKLS0tIFpvd2RhQW5tMTkxVkZmZ2x4dE5L
            eWFyNllpaGgwT0FML3piYlZ3dU1uQTQKVxS5T3i9bISxN8h1oY+QfTwgtEbkiJHE
            TiTZfAITXhwxFt/Xww5OXZ84dcXiNfQoxtoEIVT30SS0N+MSXlVWMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-24T13:55:22Z"
    mac: ENC[AES256_GCM,data:lX6/BKF4bLRQAbT96qHJmJWNkiVyX+UB2qAis4oO98QlrrcaypnQpxVjWSRUEFglcD0XfP4he5bXJTSovrD37iVqdJBNS3nk+eFzEgbV/N6eMlDRNwUqYdpM+eQHdWQVc64DRQPpNWWx9JTAzuWtRr+veJltODhL9qij1n2/B+k=,iv:74XZxl5uUULoNaxApqnIAGcZ6ID5jEnUo6b1InAqXU8=,tag:CfPv658pj3kRntXZZbRUmQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
