#ENC[AES256_GCM,data:NTRtTCrU1FnU6QHPykc8kdAaf0m9GPVqkIsSOz+iciAwmak4kmZQRJYxi+hTIOCMPL9QEMd3nCg/8HD/aMIqNw2h10zUZbgr21hK,iv:mynB8WDmdXPEWgNJIBsTLsmVTOiLYCGtQe+r4COBn54=,tag:y3Oa+i+P5mTSXo7vTnShrA==,type:comment]
#ENC[AES256_GCM,data:Am3sq2xZi7MVYuvRutyJnTTWBak=,iv:4lLISe4g9aCHzZS3qo4Q2Te7B1t6mNJ8OIKeWOgBRT4=,tag:FoXKN5rf+AGrdk7IJ6Iv9Q==,type:comment]
#ENC[AES256_GCM,data:9YzSN60UbKeW4vBIO1Pj79I3UffB1w4u+J/ZC9xob+/KTywqXkL18K9zzaY6JRUdWyfVmmGYlhtCsW2bYaU8,iv:PqgXljDQd2d1jZoRi2hV0lkJ0RGHt7gFFxknb/1ZvIM=,tag:IiKiZvPkZHOSjmvhr0pKFA==,type:comment]
#ENC[AES256_GCM,data:gX5HjA/y934WGOJP6Z5lbEuE7l+TX+caA4tQrKDUK12gMVwJ5Jip2Io=,iv:ItYRQfQ2JoAe8fBfoo2vVfCS1hC3Crg9cm24DaYbM34=,tag:U33qh4kfb/FtCZ3cLYbI3w==,type:comment]
#
#ENC[AES256_GCM,data:SP0YBz4a0y3LjpGz4oB7JMpvSYl5ruz9sSnsSUMsbc1DsA1maceLSyQDNkY9dwz1Qb8FuGE8tHd+Q95XbChU072KCWJC7Gdx,iv:tIKUOnzezbz3pFLK+yltO1+78UwECBwsnlvmcNTJCXI=,tag:wG3YW0PLGHzDTku4LsU2KQ==,type:comment]
#ENC[AES256_GCM,data:UEAm3CWL57zdNovIAYrMft7CHea26cAOvvXEon63yFH6RslrPJjODJbPhrms3tCVJyLF6F973EupwdJVSXW9JEWqaKKu2DBpITo=,iv:u2qzVPF8wl4Rz17Ac0xltzdpOBnoysBGpsM/juAk8ko=,tag:nntOId+QWMcAq+ybtrpOUQ==,type:comment]
#ENC[AES256_GCM,data:DjdobYZTJhGSUC4+GyihJdqm7x3WzDqbzH7YJfViSiCwlbP4F/zCEcih4dHmx9bN6rHJ64nJ1dLpgMtihhDInVPEzuqZQEQ=,iv:V36PYV5Hf9KTRM/wliRs/+bPjViNfg6aBlBBn8anRGk=,tag:CuSrK0stgIg2CugftRBdhg==,type:comment]
#ENC[AES256_GCM,data:o1RTkf67deIHy3mCYMZ3gQrFLr0rUul7dOK7u5vsP89+LT+Yrm8mmRiM/AVfS3mErOuq+idfbahEmqE/Uyzpad1J+zxS8dH667nx,iv:nl1Uw8klCXt0v+t07UzaLdsfiTvSJtjqIMJz/D2fuFo=,tag:bckvPx212BgeKKURjqp9EA==,type:comment]
#ENC[AES256_GCM,data:1Q1zvJYJRiWBj78TCs7FzyVzp83S9aa1sR9uyR8AOoOTNq3zT8Tnv8r22qe/pzb7IuhT0bH4UVFTaVjYMg==,iv:YkWgJsABCjVKIsvIwxf1DvTEE+6Sxi1PT6XLmNvFtDE=,tag:Air1Hpn27s5ZCf3xxHniCQ==,type:comment]
#
#ENC[AES256_GCM,data:XMIXIdv+Xqljm2wZ0Nu8peDAOclWMigY2tkURJM8UlYgd4s4hfbu/sROCECg8gLA1ghj4c5Nkzi2HyJ+aPGQgh9RhIqi,iv:9VpHmTdcrf1oVOUBZ5996exlyqWTZe2tLiiFGqHChdU=,tag:UZcThw+hDSHwKezfh1azrQ==,type:comment]
#ENC[AES256_GCM,data:Cc4ntSVja5Pvy6uzt9K6D9nh+sZWeip1ZlIQEWG/zqs28jSarItWXPMdK9smcj/V/y+m7aUdbyMyeYteY0fPRk4jtNsiO3sFl6cifu4YDliH,iv:3sqWj/bTli2aTtg2qdtEIYtxlprmHXt7UPGC4kWldWI=,tag:+T0RDLR6wmMBL0rJGyPhoA==,type:comment]
apiVersion: ENC[AES256_GCM,data:vzI=,iv:jaG7fDtmD4YAbxQrJHyOmW4pkvzSs18E35pTvmCGbVo=,tag:duWVBn7GX8Q2Bl97AU083w==,type:str]
kind: ENC[AES256_GCM,data:66B9hJ8g,iv:dqYK/wcVERw5LfD1T32iaBFQd0WPkKpiLvoZBmbC16Y=,tag:lvQRQPjnPltxOOgTpXdY5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B5UZMFIwLCHCLbV4TyL/LuyH5mPfU0KsTy+xGQ==,iv:jpRsMxOR0Ges0PCHaII/cN4U5GYW0nl8QTc4bFSg6Fw=,tag:jRIAEGqFnzPC64tsMEL4CQ==,type:str]
    namespace: ENC[AES256_GCM,data:t14PPeeudzE=,iv:sJC+33AjkgtqLk54gd2eo2S1tT04mkHeNWMp4s/vHhg=,tag:mJgUK5XeZ+4C7TyCSqaiiw==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:nZcTPggwPds3HmZ4WxklkT1Gg+bn2ekKd1lwPI1ehy4JtxrWHoRDDXwwpLB9JvZ4Wz5xMuqMkifjfJvow7RabVCB,iv:Simrvs4syMp43u2HZ7AmmLJM8g0xzX0STJ85LyIAvC4=,tag:ztauhPuqgMW59DWD1bAmjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cjNyOE5oVHRyN0Jkbk5L
            K3UwWE43b2doY0Q3dWhSazVETGd3eWxBVmhJCkpTY3VCeWVqVHhzeHJQWmpBU3I1
            dUxQS2lsMDg1NkJPU0F1WUk4MDhoY0UKLS0tIFpxeVEwTVEvUitKOWk4RWN2cW1U
            S01DRmtNS1BmZHZGQi94OGM0aFJEakUK407pcQBIZsDBOPOorKArofGaj87hJD9r
            oY96BNxuJiyIOPMGWJnAvBmusI0USvth+c+AvIpi0mSlTM5WwP5m3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-16T16:07:58Z"
    mac: ENC[AES256_GCM,data:FAdPNEqGXl5vI1IxLxPHxTQIWF8GxSp9Ggw4pt+G8rVghYdQP84EwHMJDVt15Qku3bXs9DGLS0pa0LDdzEntjbFPjtKNuShqONnJnUjxFzp1+WQ/+J2MySGaogfkRN/KYg9KVzfAWTWP1SOfBKNzaM1lNXh3wFa9YmlM3qABY20=,iv:7SZyF/UTteixmKSr3esevEHgPqnFCqTcr4u+6QqAztE=,tag:SyunirlJE+2eYWT0Bp1Ubw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
