apiVersion: ENC[AES256_GCM,data:eyI=,iv:FpWqz1rfQ6JqVAKi+1ziWqqOetmUi52jpbozjFKdiuc=,tag:+mODV+yQYBFBe9rGQQTD/w==,type:str]
kind: ENC[AES256_GCM,data:7B1x2hiM,iv:5njt2LPNFMsFUeacnikfj5WEE5eUF7LmHkJ6RAtG6+w=,tag:SKWHG9ynUPj0aSQ8VsaeOQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wk+DgOOj+4xlzWp6R8lD,iv:ied8ojdIuw5QpQRVZwrRS16N7XW0ERhu9M/kwAd4P9U=,tag:+jPYELPaFubG99bi2ehgRQ==,type:str]
    namespace: ENC[AES256_GCM,data:xE1JpNSLH4zJ3Nf8mSA=,iv:xGey5Pn7oA6BQX9vhmJbnUJge6heekhFBF7hPlgIiVc=,tag:h5j1+5jw8+JJUJIEiMAgkA==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:tF5TTQaMQHgd3VrXFpU1M5xlPfelApE2rEICwsl1W39KUkM4UV55J6rOJFRIL0OctYopn//+MBhsU4fQXvnfleoO,iv:k25keu6q5I9IUSzwuE1rpwiK2STHTE1oigBqUzSeitU=,tag:mUJixUE0r+YcQqDNUlkotQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdStOci9SZTRqREhlMnM0
            dWx6UTdSUHZESERpbjlheWZEY0hPVTRHeXdzCktUTjN2cFdvS2NWMGY3a1RHTXZt
            UGVrcXRCWlg1V0ZsM0VMV0VyUjZSeXcKLS0tIHZTSWdYdVZYWFhBM3pUSTgwTTJB
            VFdZTWh0SlBaeFJsZUYybVJ2ZTBIYUkKckzoiHAi/xftAP536onkPqx6EIllDthe
            8OevslUCDPzMvqaPw2s+Rqo13lZEBEPfPnDwBeh6mSeSiUjS3DcqHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-15T18:04:50Z"
    mac: ENC[AES256_GCM,data:6TKTv5nWGgL808Xl58HMKQsGN8gXiawDMVIbFWbIM+4uuShWwFNRfY2nbIDTCRrY39QQQtz8rIE9iA4PFXDz/zDk3XJ2wZJH6q/qImZHJsEVr7VxyQF2onEicgncggRTlA8QJ6KF32MQAs3V18aw9WwDUtCUS70lAidJbFv8fzI=,iv:9N0fNeDVL0wgsieSBbWIvEO1mD7bQqLdnS50pA61tpQ=,tag:HJnEOGUxx/x3npwZp8sZOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
