data: ENC[AES256_GCM,data:tLhKkrs7VqP8b3UeV4WIc49RgnZl7yApFcicI2xAxpd4ACcBvvQUoxKEd6Onfjk/WjOPnijDnWr6++uwXVibmA==,iv:l9gtbIpisNZkDroJMKQVEQEg4enB/+no6GTWQrGfgfg=,tag:tEvv2MA/WV2p5er8OTY1ww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTEZubEorWFdLYTVVNnc0
            NFdVWjRjT29FT05VSy8zd1NRcWc3QTFhY0ZvCm95bUc3KzVZM2dMTzlUVlpXZVNS
            Tk10ZkZPRGZjalE0SkdIRGFsU0c1d0kKLS0tIHVyMVlKZ3RtMTRGZktxNU94MnlZ
            TkZzdStIcG1yVGZHWmNoU3BYY09jZDQKEx9PYptujTG1zZlo1e/+0xP7gBf3at0E
            F+jFD9RIiCieSyEa/WlshU71PCsceBtZMb8AeX1CoIKihwvZzDtNYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-15T17:02:37Z"
    mac: ENC[AES256_GCM,data:A1CvG/hV7cIDq2/18BUSlJGV16U17f7r47cu8Ro/W22VfPX4NOmgROqGTc9fBTouZtfk5AtD9RByHx+A7XsQMYqNerzpf7/MryoVxjGmUZ3nzz+Q+Af9g8Ls0iSQvXzsSGQKUj+IgW43V02E9KX9tKrRrUQJmbRauAOHjFm75fE=,iv:bdFRG/MwDcgFsGcM2Bf8CJJYVVYK6TS/X/Sjh61h1sc=,tag:5WMvvBC+1oCfeL47hIkEkA==,type:str]
    version: 3.13.3
