server:
  interface: 0.0.0.0
  interface: ::
  do-ip6: yes
  access-control: 192.168.0.0/16 allow
  access-control: 172.16.0.0/12 allow
  access-control: fd3d:b17d:9f8e::/48 allow
  qname-minimisation: yes
  domain-insecure: "lan"
  private-address: fd00::/8 
  private-address: 192.168.0.0/24
  private-domain: "lan"
  private-domain: "jakerobb.org"

remote-control:
  control-enable: yes
  control-use-cert: no
  control-interface: /var/unbound/unbound.ctl

forward-zone:
  name: "lan."
  forward-addr: 192.168.0.1

forward-zone:
  name: "."
  forward-addr: 1.1.1.1
  forward-addr: 1.0.0.1
