data: ENC[AES256_GCM,data:689cEpNKNrDML8gmqNDPkhzYivEu,iv:za9W+lsmjJ3mYAqZPJYMTHIagLpY/wrF1SVgsDIcdTc=,tag:9aLDxXJI0QrjVVmB0GdT6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZ2QzbENhMll0aTV4U2Vv
            R0gzbVBSN2pTSkRmcTB3VDd3a2s1OU5uL25nCjR4cWdVV1RpN0YvS0R1bm9nZjIr
            b3F0aUJFL0hQZTJjRzc1ZmpRTFgvZ2cKLS0tIEk2VjArTEROcHUyOWlKZnVObVht
            NTg4UnNwcmhqeTBxaldwMEkxMGFEdlEK28cKOpxF1UKpCKzVoPuaAIOnVjcW4bam
            ayuj+MwsNeFCH4ZlH1WdrPNf+4zhKcxypL6bdxL9QEJZ6iMiPo1yHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-15T17:02:37Z"
    mac: ENC[AES256_GCM,data:qdLIik55tfhHIZHe8pqjpOYmO51ykltaP0sok6UKnAXLj2KMvO0c8eLKmpVl4dsi/S80SRI2YXuwcZkTQXP63dd9QQhQzBN/AS7LUsynXQjGFY74HAymCAb+4r7falWPBQarDO9BKcgwWlDibC6lXrIRw68pIK5Ou6EjaxYtLo0=,iv:5/BaBMOq2v+QcpgrDsL/E64AXcyJdBW65c4RysPmECI=,tag:JSsU8L0iIkV0GEsqxqP81A==,type:str]
    version: 3.13.3
