version: ENC[AES256_GCM,data:9Q==,iv:S0OQ3lsk3tBolOh+zoEg30EByRxvj7mLTSeIJBqrUZQ=,tag:61bc9Foo4YsDvHHdyX3K4w==,type:int]
mqtt:
    base_topic: ENC[AES256_GCM,data:5jkRZA4cCeT0Uko=,iv:sJ934ApVXldM8FewaR8sRkWAA1ojWjcdc9y7X0CEC8o=,tag:swP09OL18JVjjHVJWKc1+g==,type:str]
    server: ENC[AES256_GCM,data:/K312xj4jb0pYzuVVBOL7PZWY5nA7fL9VtnEBe8=,iv:XL6p3kdHet2oapNeuB7p4kY9OFK85WIEFMbZJauxFwY=,tag:U8nPhmhE4C1M1CybJA+X0Q==,type:str]
serial:
    adapter: ENC[AES256_GCM,data:xQZ9G+/w,iv:NQocZmUJo/CntKXFD+WyKRqZk1ZDcBkVNuMo+99aBls=,tag:BFel1K1yLu2+2IU18MP51A==,type:str]
    port: ENC[AES256_GCM,data:8dao+X9lg33tJ1j3zjOL7+QBRDOcioLS,iv:awcWRp14sboxqkxG2LbCcoYsGTRGcRR0u1nqKCSKwZI=,tag:mmELBbuyCZ9FnbfYp/KCrQ==,type:str]
advanced:
    log_level: ENC[AES256_GCM,data:YMPWRA==,iv:QlpL8DKsKBpxhmtfY5rMMDm8x9n7FNtuFPRII2CKtN4=,tag:c18mnWzfo1fat3wuN0e5iw==,type:str]
    channel: ENC[AES256_GCM,data:e3c=,iv:OG4Asf546aduqmWSVC6yaih++55ah+1m/Ig9qEYLg6Q=,tag:PLi3UBpGvjr4LyBS0TltBA==,type:int]
    network_key:
        - ENC[AES256_GCM,data:AXeX,iv:Dom1gGxzi9fFCbcEnrenxtn+MHs3BjuSds791AYnINI=,tag:/SbcpFhPk4DYKJM30x3MHQ==,type:int]
        - ENC[AES256_GCM,data:s7g=,iv:SBZi+dVfgfu/tSq/ivYZL2QGzpySi51CcPZ1+LejSYI=,tag:Qk8hMWKPbtBzEEWOK0CVyw==,type:int]
        - ENC[AES256_GCM,data:0pA=,iv:6KlfIyIN25GL8bC9rJXkKJ1Q3Nrvs3zeaXc6jz0gKgI=,tag:LgHoK0ASvb6BRLKdsJUsOA==,type:int]
        - ENC[AES256_GCM,data:Lnw=,iv:9oR6Gs97SWVZDpO6dtnFqkjRD2jnnw4BiXwbvVy7ynU=,tag:BonFD+RuwdqtL8+svfnsqQ==,type:int]
        - ENC[AES256_GCM,data:YbIB,iv:UkjoETNGm1bCj11UxiZb6HofgF2dJyaYJIhmlnvQKlE=,tag:oR6ZkhE2vnycJwqnzFh/ww==,type:int]
        - ENC[AES256_GCM,data:mOY=,iv:PQ4SsGdEQ2pjMlpD/wILM28q9/nY2Mf3fYrDNW89PRI=,tag:vZwpgYmF3DxICufCK+VEUQ==,type:int]
        - ENC[AES256_GCM,data:8hw=,iv:XphWZYQ4/+bbZxl+v8qhCvhb5BncWrARU7sKdiRtcr8=,tag:hAAlbb6w9ZkxBa0WMh7c1A==,type:int]
        - ENC[AES256_GCM,data:PFs=,iv:N60zXfaQO19I+BTKUo/S61og/jkhnOiJEhJfkiiqMBg=,tag:Qu2NUVf5NgFWDjxCOtf3TA==,type:int]
        - ENC[AES256_GCM,data:3Y51,iv:d0gFyIME5wp9qzCTQibJ16IBuxWKG1U2I8jO0CWrWB8=,tag:7cwYn12BGqFNtCDeYYU2Ew==,type:int]
        - ENC[AES256_GCM,data:5uI=,iv:GLIV0VEoBTvnc6eK6vlM6qZUr7qJtX7l1vrDDaYQ5n4=,tag:BS0UzXGNNxlWcVAd73ICrg==,type:int]
        - ENC[AES256_GCM,data:Tg4=,iv:f9YeUqTYWJnGaI6k9fgMQ+QDzWyzXnVdE8O+PiwVyOQ=,tag:y5BqZEaUD9W7bg18T79SAQ==,type:int]
        - ENC[AES256_GCM,data:u2nA,iv:QPfpu3P/sq/l/m3tHFtZ4wZZ+pDsetEQ5JE2tUaYrq0=,tag:h9IciRYM/efw30e1yAULdw==,type:int]
        - ENC[AES256_GCM,data:FJA=,iv:039iTCAYj3io7FdzvLpTOBtQrhwR/m5SRLpc/z6nLOM=,tag:Rzz3E2LjTUn6OcABDidKSw==,type:int]
        - ENC[AES256_GCM,data:APew,iv:UhHPvkJAK/MTJx4EPnEOTJmfxVvnvoWzajHMQ7KePMQ=,tag:ai2+QEwvMoYA540eBfsYqA==,type:int]
        - ENC[AES256_GCM,data:DNcc,iv:oo7vO+21T7PvmDiahnUe44mb3MAeDPuD/c1DHeVnI0M=,tag:FX8kccnP6csP76ZeMk4XoA==,type:int]
        - ENC[AES256_GCM,data:xIgl,iv:fNKaURUKq4FGhhu5oABzvmTIFgZWWVUGPB7I1jaKzHI=,tag:qPVCr4ElY3OyzlJl4nGPxQ==,type:int]
    pan_id: ENC[AES256_GCM,data:fvVLjsM=,iv:WUwKSqupA/Z66ySA9nLf8wN87XABcHPHcwKtPtep/R0=,tag:2MCQZj+TXvAWU4CwiaesSg==,type:int]
    ext_pan_id:
        - ENC[AES256_GCM,data:Ms8j,iv:rIelWdMNETxorC8s4nlkC+rIehMiHWWmqp8SWxglFEE=,tag:Ifh3Hl0g4CrlxP6eBom8GQ==,type:int]
        - ENC[AES256_GCM,data:m5wy,iv:SCoDFWujMZTMSkGqHHCTp4YSVVYEW1i9AzgvemhOhmY=,tag:8CTMVBO2vKgsZzRR8i+bYg==,type:int]
        - ENC[AES256_GCM,data:jqDM,iv:m8Da4LbmeLXkRrm9tyw5u6+bWulvsYY+fBEWdIqrSqM=,tag:9hXXkvfHPtNmhn4VICX/FQ==,type:int]
        - ENC[AES256_GCM,data:GyPM,iv:FMZZ2W/ej6zFBDIJRhA0f95GIa29q0y6AJngT1FsoVo=,tag:ECAknw1q+xUKzr+WuJwcIw==,type:int]
        - ENC[AES256_GCM,data:F0P2,iv:zO/9sfBobu9Yert4I0v1rOVCzBBZ8fovnHSAc81RH4Q=,tag:WIDVjXNvi1UxlVjhXFyCpA==,type:int]
        - ENC[AES256_GCM,data:L9k8,iv:kD3RpovMQfEP0phI9qHEuSZwJhNxEs0bCGizcE71KI8=,tag:aylO/JpJH6mtK2lYQcqACw==,type:int]
        - ENC[AES256_GCM,data:VuwL,iv:HEr6vAN7oHVd0N8hNDXnfhD8jaGzoZvCFPhycDQS6Mo=,tag:XOFCVKhIU016XD3TaAqb4Q==,type:int]
        - ENC[AES256_GCM,data:PhXG,iv:SJteN+K01r8Plt+GyysLffWHYb+GeOmfH+BKoqZjXTU=,tag:Ssp8uwgvyHjur/EGMVH2Qg==,type:int]
frontend:
    enabled: ENC[AES256_GCM,data:FsC3nQ==,iv:mSoW8EAiJgmPmvrG4G1TlVmFAK6FMBYZf0xT6epZLnA=,tag:a6bH02ngsiFTVkFb1186xg==,type:bool]
    port: ENC[AES256_GCM,data:2tVuqA==,iv:jwkQzzn3r9jqjpoFofco2Wu2nbZsYFHIQAuUzjWRmAI=,tag:JYJPvqAMKnZPUDyJBFHxQw==,type:int]
homeassistant:
    enabled: ENC[AES256_GCM,data:LnkF5w==,iv:6Sg9jQTyAyrs0DYo6dwJQl6lDucZYtImX4EJcVeZ7Dk=,tag:ZDZs/TkUnsgFkIWibHC7kA==,type:bool]
devices:
    "0xa4c138fb0c367e41":
        friendly_name: ENC[AES256_GCM,data:XOW9focTQTlLt2h7Idc=,iv:2rwfwiQy3p3Kv38dSloyzHHB5uVcsB2UDplWiTA8pHs=,tag:noPFh4yIa7VQLGSH9UW/ZQ==,type:str]
        transition: ENC[AES256_GCM,data:bA==,iv:nKFhuO4mfqTsYjycm2dYJ/ZeevqIWznKgL/A92M6xxE=,tag:2qdLWcLxVCpAY/QyDwdhjQ==,type:int]
        color_sync: ENC[AES256_GCM,data:h1JwFg==,iv:bJKE9/l3wUG5uLzk56/x+a/zajxvdkGtgGSKzV96C1g=,tag:XV1YOwnIPuWH0Ne5caqoSw==,type:bool]
        state_action: ENC[AES256_GCM,data:E9Cz6Ws=,iv:b3h6a91CGyhRQRmdYMxn3hYGAoGEJ5j+3rwP48zRPio=,tag:BO49HvBwc+LacFldLq6cMg==,type:bool]
    "0xa4c1383ba275d419":
        friendly_name: ENC[AES256_GCM,data:pJwlLgx5GmGUx5uKAnk=,iv:MhaFRQqLSU89EvkuvyhHLbUSWRSZroyQsTkbPP6tJVo=,tag:WK9r31qUJK/l1mgg8WeakQ==,type:str]
    "0x001788010e550f76":
        friendly_name: ENC[AES256_GCM,data:l8RiqCilVGsGKw78jM1o,iv:xIiBfeqJ/OYUYpNppkKoDPJFsxF0/otzI+mDKcIvzAw=,tag:2++Dd3h/fC+DGkQrH34XuA==,type:str]
    "0x4ce17552e5430000":
        friendly_name: ENC[AES256_GCM,data:ZiyO0JlX,iv:rRHpsrcQkIQwgEYjjmL/Lao9gvx2nZy687RsJZhBsCI=,tag:+1Y/8Kk3Qwo248l3kC+j4w==,type:str]
    "0x4ce17552bf330000":
        friendly_name: ENC[AES256_GCM,data:ajtXPraiP42Ahuz+K0ilQfJtmw==,iv:j/vKaMX2/arrsnu/yIZ2eujn/ivQtIy3jzfAscP6UqU=,tag:jkq7dAhJo4zdY4eVfid50g==,type:str]
    "0xa4c138ed8205dd86":
        friendly_name: ENC[AES256_GCM,data:p/qndQBLNd7zkn+M97Q=,iv:z+YsPTiPccWtYco3C41AMiNtJYjuzUny7NVBQbfa4UE=,tag:tQdp2UAYlNa2K+r78jx9uQ==,type:str]
    "0xf044d3fffe6cfb45":
        friendly_name: ENC[AES256_GCM,data:939aB7Tl3SZf6k52fVCTNOSFhSjZ+o8=,iv:Cuc8Hqv8dUdDorowZTPcGHmbHQYfXeujnc6+jj/WN1s=,tag:fEgBLOSG2pxL3vOh18j+AA==,type:str]
    "0x001788010f27096a":
        friendly_name: ENC[AES256_GCM,data:4oOb5NQajRw=,iv:Vo00NKVcEvyEQZvhTlOL61n0F4lhOSjFkpAC4bE5FdA=,tag:wRLf6VlBhU7KxAlQb/V4Fw==,type:str]
    "0x001788010f26fef7":
        friendly_name: ENC[AES256_GCM,data:tf1Ukq3p/iKi,iv:1ipa5REYf3XjyAoIZ6EjbYCX2A2BpAtdqUswjcIhFhM=,tag:tZuH5AYcc3S61+oJnsYj1Q==,type:str]
    "0x001788010f270846":
        friendly_name: ENC[AES256_GCM,data:FzK6EhxLiQHp,iv:ZGyueBBaM5/Tbu8gzwxKf9g4e/CKYIeiKvjwolYhgYM=,tag:VOKUyORp2i/qQ32Oja8kxA==,type:str]
    "0x001788010f27001e":
        friendly_name: ENC[AES256_GCM,data:87i701S1IM8=,iv:tNjDgngzouOWx5kFrV1utY5Zvsxyd/OP9JVN+ejrSuY=,tag:RFFVvpX+WLlohYkLZKnDig==,type:str]
    "0x001788010f26ff3b":
        friendly_name: ENC[AES256_GCM,data:wS8Nhx1N28mJ,iv:47nPb8baRUfnK62ocBsl3j9yR4KAIpIA4lO7cUHAkU8=,tag:ueOlO1LmAnIPxPPytGnjDg==,type:str]
    "0x001788010f270056":
        friendly_name: ENC[AES256_GCM,data:kjO9yvLJ854I,iv:6unEtkDEV4cw6Due8NV1F7b5RrauXMxQBKy6vtyvk7M=,tag:pgzStFx3Cvcy5tdYrLX2Vw==,type:str]
    "0x4ce17552e64f0000":
        friendly_name: ENC[AES256_GCM,data:9yZLAoI+31jqIDcGqNKhcnXI1ZDNnA==,iv:KkLGtyQPuwVFTnZS1ZD6Z1pXsk3B6A+knNsnmX1oD2M=,tag:7GYOj3nbV07ucSwcif/zQw==,type:str]
groups:
    "1":
        friendly_name: ENC[AES256_GCM,data:dQFiC/CPWIEfHYp9,iv:9bPwRBnSwBEaIuetPqFsCMM9sr9l/jJJpJiumI5DMyM=,tag:e7u1T7Vn0k2box+vHnNDPg==,type:str]
    "2":
        friendly_name: ENC[AES256_GCM,data:4/asYHYmKkD9MfYCTF5aecXZ,iv:NSUx2EAzUmhj5OBf2Xt9cZGJz8nbiYUvJIHci45hKjE=,tag:apH8coJ8118XlGjooRyEwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWHpxWmd0WXZEMW9KRzhk
            NCtGRzBiUHI3cVc3V3RabWpXQnBGQTZBT0VzClA5dHZWVVUwUStmVlJPbzI1azdF
            NnBZZFl5QWoxQTJEYWcwSjYzdXMxcU0KLS0tIG9IaE95MGUxTzgvREVvTDh5YUlk
            YjM3aWloSnJZaFVONUdtWHNpYisybjQKQ2nXZoTxIeqRUwMqlfsJ3iCKmDTxNpKE
            3G6YQOE6igGrQ0tVhAFpLABhabhqQrX3cTmsIQbGXgSqBZ8CESxV7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-10-01T02:51:04Z"
    mac: ENC[AES256_GCM,data:RJNBfc5vzSbvA3362Qr9F9u1MIGZEV76BlS9rTRp/XNLAUYc+auWp7WFiXgk6fkXOR0qX9eNTFVn9VP3ZDvLH9I9iq0oYSKk+IaGb/8EAIFkcPxFSyDE13u/R0d1uYcDyBQSv6LyVxyhVoE9/5dYAGSl+oQ47qn6DBejmhQl2Kg=,iv:n5Jpka7fn73rS63rRotE2QshRJTkXOJqVOUzCayG2dg=,tag:BuePN6ZWORHhkwzT6/Es+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
