#ENC[AES256_GCM,data:6kM1WV+FoWrI1plSL05MoBsyaTrGKZapXNtkB6AF3qGGC8Ls9yV5SD0D/b9ZxNQ3sZF8UjvSmFotjWvULg==,iv:9eiEVMZizKsxIz7rnO39KO3vp2rEhq/RmNZWV7d8nfY=,tag:6V3hXz1pWyMchJfCxyWxjw==,type:comment]
#ENC[AES256_GCM,data:XsdtlhS6x1XXdBu15rriV2UCsOy1MRRtsp29/OaZYah31eQV7b9R4prWsNFX07TXEF78aZQL4rUWHT80gY3hyTrDtXd5K27/,iv:hs/FzhjK7tUT/B/h1+p0CePms5EYX42afD5cTFJszGI=,tag:mreumcWldI+tNGdoTytWOQ==,type:comment]
OFFICE_UPS_NUT_PASSWORD: ENC[AES256_GCM,data:XbY5NtZzARSsnmRNKwTPO4RPsw==,iv:KMc2fYyD0jO1kDubSYABCcphklU0cB4R7uy3AD/Xbhg=,tag:+vLyhBRa7ShGZE+xQ5W7pQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZlRWQ3BwVnU1Vmk0VkxK
            b3VGN0RQNmRodzBqNHFIaWxqK2NLc3g2UmdVCjVLSnFJQ2xYT2tBVWEvWm90Qk5t
            bGNta2hWT2RKamQzZEl2UUpyL2J2T0UKLS0tIEUrL1d2bjdyWVBncFR4NFpCTzIx
            YWtXVzQzMTk5T1NNcWtxRERLN3NUYVEKh2VQSOYtqFTz6NfAkFwbbip4WZ/OIudX
            g5V7Ks907G48HoOUqqv5ghdRheGeBJ1SA0upEpBKFnNVR9lf2ciHRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nqvgqc45f5j9y9ch0lyccdefeazs26xkp732rujp23nqeqmdjefshruqs8
    lastmodified: "2026-09-15T17:02:37Z"
    mac: ENC[AES256_GCM,data:YwjBLxWugv1VGvtGOKL0h2FDh+wlf3XLdVgYxQVU7Xpeoo6sXVBNBCQJcUEXtaZzR8joauFaU4txZ2LB0IQk7R/zlkC9H3ohtWjRycW0kzObjrQoGo8KtGfu9btvMb5Ly2bPdS4Nh+UtZ1+LHVdplupGBsr+X2m7HOdW1BiO/QI=,iv:BDGYKsR4BfFuCpS2OVMSL2JdduAyr3Tf76XKNJ0Hafo=,tag:RR5cgRT04t8b1U7R22f1+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
